const canvas = document.getElementById('game');
const ctx = canvas.getContext('2d');
const scoreEl = document.getElementById('score'), bestEl = document.getElementById('best');
const startScreen = document.getElementById('startScreen'), gameOver = document.getElementById('gameOver');
const endScore = document.getElementById('endScore'), endTitle = document.getElementById('endTitle');
const playButton = document.getElementById('playButton'), retryButton = document.getElementById('retryButton'), soundButton = document.getElementById('soundButton');
let W, H, dpr, player, items, stars, particles, score, started, last, spawnClock, speed, combo, comboTimer, shake, sound = true, audio;
let best = Number(localStorage.getItem('star-hopper-best') || 0);
bestEl.textContent = String(best).padStart(3, '0');

function size() { dpr = Math.min(window.devicePixelRatio || 1, 2); W = canvas.clientWidth; H = canvas.clientHeight; canvas.width = W * dpr; canvas.height = H * dpr; ctx.setTransform(dpr, 0, 0, dpr, 0, 0); }
function reset() { size(); player = { x: W * .25, y: H * .68, vy: 0, r: 16, tilt: 0, squash: 0 }; score = 0; speed = 190; spawnClock = combo = comboTimer = shake = 0; items = []; particles = []; stars = Array.from({ length: 72 }, () => ({ x: Math.random() * W, y: Math.random() * H, r: Math.random() * 1.7 + .25, phase: Math.random() * 6, drift: 12 + Math.random() * 48 })); scoreEl.textContent = '000'; }
function tone(freq, duration = .08, type = 'sine', volume = .055) { if (!sound) return; const Audio = window.AudioContext || window.webkitAudioContext; if (!Audio) return; audio ||= new Audio(); if (audio.state === 'suspended') audio.resume(); const o = audio.createOscillator(), g = audio.createGain(); o.type = type; o.frequency.setValueAtTime(freq, audio.currentTime); g.gain.setValueAtTime(volume, audio.currentTime); g.gain.exponentialRampToValueAtTime(.001, audio.currentTime + duration); o.connect(g).connect(audio.destination); o.start(); o.stop(audio.currentTime + duration); }
function burst(x, y, color, amount = 12, power = 130) { for (let i = 0; i < amount; i++) { const angle = Math.random() * Math.PI * 2, velocity = power * (.35 + Math.random() * .8); particles.push({ x, y, vx: Math.cos(angle) * velocity, vy: Math.sin(angle) * velocity, life: .35 + Math.random() * .35, max: .7, r: 1.5 + Math.random() * 3.5, color }); } }
function jump() { if (!started) return; player.vy = -405; player.squash = 1; burst(player.x - 10, player.y + 8, '#75e2d8', 6, 60); tone(460, .065, 'sine', .045); }
function begin() { reset(); started = true; startScreen.classList.add('hidden'); gameOver.classList.add('hidden'); last = performance.now(); requestAnimationFrame(loop); }
function finish() { started = false; shake = 10; burst(player.x, player.y, '#f0768f', 24, 220); tone(105, .34, 'sawtooth', .08); best = Math.max(best, Math.floor(score)); localStorage.setItem('star-hopper-best', best); bestEl.textContent = String(best).padStart(3, '0'); endScore.textContent = Math.floor(score); endTitle.textContent = score >= 100 ? 'Cosmic legend!' : score >= 55 ? 'Stellar flight!' : score >= 25 ? 'Nice flight!' : 'Keep hopping!'; gameOver.classList.remove('hidden'); draw(performance.now()); }
function addItem() { const collectible = Math.random() < Math.max(.25, .39 - score / 480); items.push({ x: W + 40, y: 82 + Math.random() * (H - 160), r: collectible ? 10 : 17 + Math.min(score / 170, 4), kind: collectible ? 'star' : 'rock', spin: 0, pulse: Math.random() * 6 }); }
function update(dt) { speed += dt * 2.5; spawnClock += dt; if (spawnClock > Math.max(.48, 1.05 - score / 250)) { addItem(); spawnClock = 0; } player.vy += 960 * dt; player.y += player.vy * dt; player.tilt = Math.max(-.42, Math.min(.58, player.vy / 640)); player.squash = Math.max(0, player.squash - dt * 4.5); if (player.y < 30) { player.y = 30; player.vy = 0; } if (player.y > H - 28) return finish(); stars.forEach(s => { s.x -= s.drift * dt * (1 + score / 360); if (s.x < -3) { s.x = W + 3; s.y = Math.random() * H; } }); items.forEach(i => { i.x -= speed * dt; i.spin += dt * (i.kind === 'star' ? 3 : 1.6); }); items = items.filter(i => i.x > -50); comboTimer -= dt; if (comboTimer <= 0) combo = 0; for (const i of items) { if (Math.hypot(player.x - i.x, player.y - i.y) < player.r + i.r - 3) { if (i.kind === 'rock') return finish(); i.hit = true; combo++; comboTimer = 1.8; score += 5 + Math.min(combo - 1, 4); burst(i.x, i.y, '#ffdc81', 15, 145); tone(690 + combo * 35, .08, 'triangle'); } } items = items.filter(i => !i.hit); particles.forEach(p => { p.x += p.vx * dt; p.y += p.vy * dt; p.vy += 180 * dt; p.life -= dt; }); particles = particles.filter(p => p.life > 0); shake = Math.max(0, shake - dt * 24); score += dt * 7; scoreEl.textContent = String(Math.floor(score)).padStart(3, '0'); }
function drawItem(i) { ctx.save(); ctx.translate(i.x, i.y); ctx.rotate(i.spin); if (i.kind === 'star') { const s = 1 + Math.sin(i.pulse + performance.now() * .006) * .1; ctx.scale(s, s); ctx.fillStyle = '#ffdc81'; ctx.shadowColor = '#ffdc81'; ctx.shadowBlur = 17; ctx.beginPath(); for (let n = 0; n < 10; n++) { const r = n % 2 ? 4 : 12, a = n * Math.PI / 5 - Math.PI / 2; ctx.lineTo(Math.cos(a) * r, Math.sin(a) * r); } ctx.closePath(); ctx.fill(); } else { ctx.fillStyle = '#f0768f'; ctx.shadowColor = '#f0768f'; ctx.shadowBlur = 12; ctx.beginPath(); for (let n = 0; n < 9; n++) { const r = n % 2 ? i.r * .74 : i.r, a = n * Math.PI * 2 / 9; ctx.lineTo(Math.cos(a) * r, Math.sin(a) * r); } ctx.closePath(); ctx.fill(); ctx.fillStyle = '#9c4563'; ctx.beginPath(); ctx.arc(-5, -3, 3, 0, 7); ctx.arc(6, 5, 2.5, 0, 7); ctx.fill(); } ctx.restore(); }
function drawPlayer() { ctx.save(); ctx.translate(player.x, player.y); ctx.rotate(player.tilt); const s = player.squash * .18; ctx.scale(1 - s, 1 + s); ctx.shadowColor = '#7de9e0'; ctx.shadowBlur = 23; ctx.fillStyle = '#75e2d8'; ctx.beginPath(); ctx.arc(0, 0, player.r, 0, Math.PI * 2); ctx.fill(); ctx.shadowBlur = 0; ctx.fillStyle = '#151637'; ctx.beginPath(); ctx.arc(5, -4, 3.3, 0, 7); ctx.fill(); ctx.strokeStyle = '#151637'; ctx.lineWidth = 2; ctx.beginPath(); ctx.arc(2, 2, 8, .15, 1.2); ctx.stroke(); ctx.fillStyle = '#f7f3ef'; ctx.beginPath(); ctx.moveTo(-14, 4); ctx.lineTo(-28 - Math.min(player.vy, 0) * .015, 11); ctx.lineTo(-14, 14); ctx.closePath(); ctx.fill(); ctx.restore(); }
function draw(time) { ctx.clearRect(0, 0, W, H); ctx.save(); if (shake) ctx.translate((Math.random() - .5) * shake, (Math.random() - .5) * shake); const bg = ctx.createLinearGradient(0, 0, 0, H); bg.addColorStop(0, '#1c1d4b'); bg.addColorStop(.52, '#121538'); bg.addColorStop(1, '#090a20'); ctx.fillStyle = bg; ctx.fillRect(0, 0, W, H); const glow = ctx.createRadialGradient(W * .84, H * .18, 0, W * .84, H * .18, W * .44); glow.addColorStop(0, '#6e55b929'); glow.addColorStop(1, 'transparent'); ctx.fillStyle = glow; ctx.fillRect(0, 0, W, H); stars.forEach(s => { ctx.globalAlpha = .24 + Math.sin(time * .002 + s.phase) * .22; ctx.fillStyle = '#e8e3ff'; ctx.fillRect(s.x, s.y, s.r, s.r); }); ctx.globalAlpha = 1; ctx.strokeStyle = '#625c95'; ctx.lineWidth = 2; ctx.setLineDash([5, 13]); ctx.beginPath(); ctx.moveTo(0, H - 25); ctx.lineTo(W, H - 25); ctx.stroke(); ctx.setLineDash([]); items.forEach(drawItem); particles.forEach(p => { ctx.globalAlpha = Math.max(0, p.life / p.max); ctx.fillStyle = p.color; ctx.beginPath(); ctx.arc(p.x, p.y, p.r, 0, Math.PI * 2); ctx.fill(); }); ctx.globalAlpha = 1; drawPlayer(); if (combo > 1 && started) { ctx.fillStyle = '#ffdc81'; ctx.font = "700 13px 'Space Grotesk'"; ctx.textAlign = 'center'; ctx.globalAlpha = Math.min(1, comboTimer * 2); ctx.fillText(`×${combo} STAR CHAIN`, W / 2, 66); } ctx.globalAlpha = 1; ctx.restore(); }
function loop(now) { if (!started) return; const dt = Math.min((now - last) / 1000, .033); last = now; update(dt); draw(now); if (started) requestAnimationFrame(loop); }
function act(e) { if (!e.target.closest('button') && started) jump(); }
playButton.addEventListener('click', begin); retryButton.addEventListener('click', begin); canvas.addEventListener('pointerdown', act); window.addEventListener('keydown', e => { if (e.code === 'Space' || e.code === 'ArrowUp') { e.preventDefault(); started ? jump() : begin(); } }); soundButton.addEventListener('click', () => { sound = !sound; soundButton.textContent = sound ? '♪' : '×'; soundButton.setAttribute('aria-label', sound ? 'Mute sound' : 'Enable sound'); }); window.addEventListener('resize', () => { if (!started) { reset(); draw(0); } }); reset(); draw(0);
