const canvas = document.getElementById('game');
const ctx = canvas.getContext('2d');
const scoreEl = document.getElementById('score');
const bestEl = document.getElementById('best');
const startScreen = document.getElementById('startScreen');
const gameOver = document.getElementById('gameOver');
const endScore = document.getElementById('endScore');
const endTitle = document.getElementById('endTitle');
const playButton = document.getElementById('playButton');
const retryButton = document.getElementById('retryButton');
const soundButton = document.getElementById('soundButton');

let W, H, dpr, player, items, stars, score, started, last, spawnClock, speed, sound = true;
let best = Number(localStorage.getItem('star-hopper-best') || 0);
bestEl.textContent = String(best).padStart(3, '0');

function size() { dpr = Math.min(window.devicePixelRatio || 1, 2); W = canvas.clientWidth; H = canvas.clientHeight; canvas.width = W * dpr; canvas.height = H * dpr; ctx.setTransform(dpr, 0, 0, dpr, 0, 0); }
function reset() { size(); player = { x: W * .25, y: H * .68, vy: 0, r: 16, tilt: 0 }; score = 0; speed = 190; spawnClock = 0; items = []; stars = Array.from({ length: 56 }, () => ({ x: Math.random() * W, y: Math.random() * H, r: Math.random() * 1.6 + .3, phase: Math.random() * 6 })); scoreEl.textContent = '000'; }
function tone(freq, duration = .08, type = 'sine') { if (!sound || !window.AudioContext) return; const a = new AudioContext(), o = a.createOscillator(), g = a.createGain(); o.type = type; o.frequency.value = freq; g.gain.setValueAtTime(.055, a.currentTime); g.gain.exponentialRampToValueAtTime(.001, a.currentTime + duration); o.connect(g).connect(a.destination); o.start(); o.stop(a.currentTime + duration); }
function jump() { if (!started) return; player.vy = -390; tone(470, .07); }
function begin() { reset(); started = true; startScreen.classList.add('hidden'); gameOver.classList.add('hidden'); last = performance.now(); requestAnimationFrame(loop); }
function finish() { started = false; tone(120, .28, 'sawtooth'); best = Math.max(best, Math.floor(score)); localStorage.setItem('star-hopper-best', best); bestEl.textContent = String(best).padStart(3, '0'); endScore.textContent = Math.floor(score); endTitle.textContent = score >= 75 ? 'Stellar flight!' : score >= 35 ? 'Nice flight!' : 'Keep hopping!'; gameOver.classList.remove('hidden'); }
function addItem() { const collectible = Math.random() < .34; items.push({ x: W + 35, y: 80 + Math.random() * (H - 155), r: collectible ? 10 : 17, kind: collectible ? 'star' : 'rock', spin: 0 }); }
function update(dt) { speed += dt * 2.2; spawnClock += dt; if (spawnClock > Math.max(.56, 1.1 - score / 280)) { addItem(); spawnClock = 0; } player.vy += 950 * dt; player.y += player.vy * dt; player.tilt = Math.max(-.38, Math.min(.55, player.vy / 650)); if (player.y < 30) { player.y = 30; player.vy = 0; } if (player.y > H - 27) return finish(); items.forEach(i => { i.x -= speed * dt; i.spin += dt * (i.kind === 'star' ? 3 : 1.6); }); items = items.filter(i => i.x > -45); for (const i of items) { const dist = Math.hypot(player.x - i.x, player.y - i.y); if (dist < player.r + i.r - 3) { if (i.kind === 'rock') return finish(); i.hit = true; score += 5; tone(760, .08); } } items = items.filter(i => !i.hit); score += dt * 7; scoreEl.textContent = String(Math.floor(score)).padStart(3, '0'); }
function draw(time) { ctx.clearRect(0, 0, W, H); const grad = ctx.createLinearGradient(0, 0, 0, H); grad.addColorStop(0, '#191a43'); grad.addColorStop(1, '#0c0d25'); ctx.fillStyle = grad; ctx.fillRect(0, 0, W, H); stars.forEach(s => { ctx.globalAlpha = .3 + Math.sin(time * .002 + s.phase) * .2; ctx.fillStyle = '#d8d4ff'; ctx.fillRect(s.x, s.y, s.r, s.r); }); ctx.globalAlpha = 1; ctx.strokeStyle = '#625c95'; ctx.lineWidth = 2; ctx.setLineDash([5, 13]); ctx.beginPath(); ctx.moveTo(0, H - 25); ctx.lineTo(W, H - 25); ctx.stroke(); ctx.setLineDash([]); items.forEach(drawItem); drawPlayer(); }
function drawItem(i) { ctx.save(); ctx.translate(i.x, i.y); ctx.rotate(i.spin); if (i.kind === 'star') { ctx.fillStyle = '#ffdc81'; ctx.shadowColor = '#ffdc81'; ctx.shadowBlur = 15; ctx.beginPath(); for (let n = 0; n < 10; n++) { const r = n % 2 ? 4 : 12; const a = n * Math.PI / 5 - Math.PI / 2; ctx.lineTo(Math.cos(a) * r, Math.sin(a) * r); } ctx.closePath(); ctx.fill(); } else { ctx.fillStyle = '#f0768f'; ctx.shadowColor = '#f0768f'; ctx.shadowBlur = 11; ctx.beginPath(); for (let n = 0; n < 9; n++) { const r = n % 2 ? i.r * .74 : i.r; const a = n * Math.PI * 2 / 9; ctx.lineTo(Math.cos(a) * r, Math.sin(a) * r); } ctx.closePath(); ctx.fill(); ctx.fillStyle = '#9c4563'; ctx.beginPath(); ctx.arc(-5, -3, 3, 0, 7); ctx.arc(6, 5, 2.5, 0, 7); ctx.fill(); } ctx.restore(); }
function drawPlayer() { ctx.save(); ctx.translate(player.x, player.y); ctx.rotate(player.tilt); ctx.shadowColor = '#7de9e0'; ctx.shadowBlur = 20; ctx.fillStyle = '#75e2d8'; ctx.beginPath(); ctx.arc(0, 0, player.r, 0, Math.PI * 2); ctx.fill(); ctx.shadowBlur = 0; ctx.fillStyle = '#151637'; ctx.beginPath(); ctx.arc(5, -4, 3.3, 0, 7); ctx.fill(); ctx.strokeStyle = '#151637'; ctx.lineWidth = 2; ctx.beginPath(); ctx.arc(2, 2, 8, .15, 1.2); ctx.stroke(); ctx.fillStyle = '#f7f3ef'; ctx.beginPath(); ctx.moveTo(-14, 4); ctx.lineTo(-27, 11); ctx.lineTo(-14, 14); ctx.closePath(); ctx.fill(); ctx.restore(); }
function loop(now) { if (!started) return; const dt = Math.min((now - last) / 1000, .033); last = now; update(dt); draw(now); if (started) requestAnimationFrame(loop); }
function act(e) { if (e.target.closest('button')) return; if (!started && gameOver.classList.contains('hidden')) begin(); else if (started) jump(); }
playButton.addEventListener('click', begin); retryButton.addEventListener('click', begin); canvas.addEventListener('pointerdown', act); window.addEventListener('keydown', e => { if (e.code === 'Space' || e.code === 'ArrowUp') { e.preventDefault(); if (started) jump(); else begin(); } }); soundButton.addEventListener('click', () => { sound = !sound; soundButton.textContent = sound ? '♪' : '×'; }); window.addEventListener('resize', () => { if (!started) { reset(); draw(0); } }); reset(); draw(0);
